/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.multilix.kafka.transaction;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface TransactionProtocol {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"TransactionProtocol\",\"namespace\":\"com.multilix.kafka.transaction\",\"types\":[{\"type\":\"record\",\"name\":\"Transaction\",\"fields\":[{\"name\":\"fromIBAN\",\"type\":\"string\"},{\"name\":\"toIBAN\",\"type\":\"string\"},{\"name\":\"transactionTime\",\"type\":\"long\"},{\"name\":\"amount\",\"type\":\"double\"}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends TransactionProtocol {
    public static final org.apache.avro.Protocol PROTOCOL = com.multilix.kafka.transaction.TransactionProtocol.PROTOCOL;
  }
}